### ISSUE TITLE
Open redirect vulnerability

### ISSUE THREAD

**Issue by ishanjain28** [Instadapp/smart-lookup#1]
This project is used in dsa-nuxt apps and is vulnerable to this issue. 

An attacker can use a url like,  https://smart-lookup.instadapp.io/%2fexample.com%2f%2f to redirect users who clicked on a legitmate link to an attacker controller website. 

It should limit where it'll allow redirecting users.

**Comment by KABBOUCHI** [comment]
updated to the latest nuxt version, it should be fixed now
